### ISSUE TITLE
Mismatch detected for 'RuntimeLibrary' on build

### ISSUE THREAD

**Issue by Martos** [techiew/DirectX11Hook#12]
Hi,
when i try to build with debug or relase X64 i received the error

`LNK2038	mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MTd_StaticDebug' in Example.obj	DirectXHook DirectXHook\DirectXTK.lib(SpriteBatch.obj)`

Thanks

**Comment by techiew** [comment]
Try changing this setting:
![image](https://github.com/techiew/DirectXHook/assets/22145177/b2f01926-b529-41dc-9c2a-a25de4ec0343)

**Comment by Martos** [comment]
Thanks, it worked !
