### ISSUE TITLE
32bit not compiling

### ISSUE THREAD

**Issue by Martos** [techiew/DirectX11Hook#13]
Hi, i tried to compile with 32bit mode selected and i have error on Jump.asm
![Senza titolo](https://github.com/techiew/DirectXHook/assets/4572919/281a83a8-3821-4890-aee8-c37dbc326a67)

**Comment by techiew** [comment]
Hi. Try the latest changes on the master branch which I just pushed, Jump.asm is no longer used in that version. Also I recommend building in Release, directxtk does not seem to want to link in Debug mode.

**Comment by Martos** [comment]
Hi, now it compile ! But when i use the dinput8.dll on release with 32 bit, i have this error on log

MemoryUtils > Hooking...
MemoryUtils > Existing bytes: 0x8b 0xff 0x55 0x8b 0xec 0x83 0xe4 0xf8 0x83 0xec 0x38 0xa1 0xc0 0x22 0x4f 0x6d 0x33 0xc4 0x89 0x44 
MemoryUtils > Failed to allocate 61 bytes of memory

**Comment by techiew** [comment]
Weird, try copying in these changes, then I can see better what's going on:
https://github.com/techiew/DirectXHook/commit/c6f01f2860cb56ebbceccc69f9e803a4223bd10a

**Comment by Martos** [comment]
Here the new log

MemoryUtils > Hooking...
MemoryUtils > Existing bytes: 0x9c 0x60 0xf0 0x0f 0xba 0x2d 0x38 0xdb 0x45 0x13 0x00 0x73 0x24 0xff 0x15 0x68 0xc0 0x08 0x10 0x05 
MemoryUtils > Instruction invalid, could not check length!
MemoryUtils > Failed to allocate 61 bytes of memory. Origin: 10030525, lower: 90030526, higher: 90030524, attempts: 0

The game I try to hook is Grid Autosport with DX11 on 32Bit

**Comment by techiew** [comment]
Turns out 32bit games in general seem to have an issue, not sure when this happened. I am downloading Grid Autosport and will be testing tomorrow.

**Comment by techiew** [comment]
I was pretty sure I had tested this library with 32bit games, but I must have been thinking about https://github.com/techiew/UniversalProxyDLL

Anyway I made some quick fixes that made it work on my PC, please test with the latest changes on the master branch.

I haven't been working on DirectXHook for some time now, but I have a lot of changes that I have done locally (and others yet to be done...) that I want to push soon hopefully. They are desperately needed.

**Comment by Martos** [comment]
I tried with Grid Autosport again, the game opening just fine ! And the render hook works too !
Thanks 💯
