### ISSUE TITLE
feature request: pause game when focus is lost

### ISSUE THREAD

**Issue by xxjddd** [techiew/DirectX11Hook#5]
Currently, while the game is paused, trying to switch focus to another application is impossible and the game will still be focused.

It would be nice if the focus of ELDEN RING was able to be changed while paused, and if an option to automatically pause the game upon focus loss was added.

**Comment by techiew** [comment]
The window should behave exactly the same way when it's paused as when it isn't. I.e. alt-tabbing and application switching should work as normal. Do you have the latest version of the pause mod? The first variant of the pause functionality was very brute force and ignored the Windows message loop, but now it performs the necessary ritual to make Windows happy.
